//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab29.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesA
    {
        public string Movie { get; set; }
        public string Category { get; set; }
        public string Director { get; set; }
        public int Year { get; set; }
        public int Running_Time { get; set; }
        public int ID { get; set; }
    }
}
